config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'url_histories#index'

  mount Sidekiq::Web => "url_histories/sidekiq"

  resources :url_histories, only: [:new, :index, :create] do
    collection do
      get 'email_report', to: 'url_histories#email_report'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url_history.rb
class UrlHistory < ApplicationRecord
  validate :url_length_must_be_at_least_12_characters

  private

  def url_length_must_be_at_least_12_characters
    if url.length < 12
      errors.add(:url, "must be at least 12 characters long")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/url_histories_controller.rb
class UrlHistoriesController < ApplicationController
  before_action :set_current_url, only: [:index]

  def index
    @url_histories = UrlHistory.all.order(created_at: :desc)
  end

  def new
    @url_history = UrlHistory.new
  end

  def create
    @url_history = UrlHistory.new(url_history_params)
    
    if @url_history.save
      flash[:success] = 'URL was successfully saved.'
      redirect_to url_histories_path
    else
      flash[:alert] = 'URL could not be saved.'
      render :new
    end
  end

  def email_report
    email = params[:user_email]
    urls = UrlHistory.all.pluck(:url)
  
    EmailReportWorker.perform_async(email, urls)
  end

  private

  def url_history_params
    params.require(:url_history).permit(:url)
  end

  def set_current_url
    @current_url = UrlHistory.find(params[:current_url]) if params[:current_url].present?

    @current_url = if params[:back]
      UrlHistory.where('created_at < ?', @current_url&.created_at || Time.current).order(created_at: :desc).first
    elsif params[:next]
      UrlHistory.where('created_at > ?', @current_url&.created_at || Time.current).order(created_at: :asc).first
    else
      UrlHistory.order(created_at: :desc).first
    end

    @disable_back_button = @current_url.nil? || UrlHistory.where('created_at < ?', @current_url.created_at).empty?
    @disable_next_button = @current_url.nil? || UrlHistory.where('created_at > ?', @current_url.created_at).empty?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_histories_helper.rb
module UrlHistoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrowserHistorySimulator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/url_histories/email_report.html.erb
<h2>Email report is being generated and will be sent shortly...'</h2>

<%=link_to 'Back', url_histories_path %>

app/views/url_histories/index.html.erb
<div class="flex-container">
  <h1>Browser History Simulator</h1>

  <%= link_to('Create URL', new_url_history_path) %>

  <!-- Navigation buttons -->
  <div class="flex-div">
    <div class="flex-back">
      <%if @disable_back_button %>
        <%= link_to(
          'Back ',
          'javascript:void(0);',
          class: 'btn btn-primary disabled' )
        %>
      <% else %>
        <%= link_to(
          'Back ',
          url_histories_path(back: true, current_url: @current_url.id),
          class: 'btn btn-primary' )
        %>
      <% end %>
    </div>

    <div class="flex-next">
      <%if @disable_next_button %>
        <%= link_to 'Next', 'javascript:void(0);', class: 'btn btn-primary disabled' %>
      <% else %>
        <%= link_to 'Next', url_histories_path(next: true, current_url: @current_url.id), class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

  <!-- Report email button -->
  <%= form_with(url: email_report_url_histories_path, method: :get) do |form| %>
    <input type="email" name="user_email" id="user_email" placeholder="Enter your email" required>
    <%= form.submit 'Email Me The Report', id: 'btn-report-email' %>
  <% end %>

  <h2>Current URL:</h2>
  <p><%= @current_url.url if @current_url %></p>

  <h2>Entered URLs:</h2>
  <ul>
    <% @url_histories.each do |url_history| %>
      <li><%= url_history.url %></li>
    <% end %>
  </ul>
</div>

app/views/url_histories/new.html.erb
<div class="flex-container">
  <% if @url_history.errors.has_key?(:url) %>
    <div class="alert alert-danger">
      <%= @url_history.errors[:url].first %>
    </div>
  <% end %>


  <!-- Textbox form to enter a URL -->
  <%= form_with(model: @url_history, url: url_histories_path, method: :post) do |form| %>
    <%= form.text_field :url, placeholder: 'Enter a URL', id: 'url', required: true %>
    <%= form.submit 'Go' %>
  <% end %>

  <%= link_to('Go to Index', url_histories_path, class: 'transfer-link') %>
</div>